# Generated by Django 5.2.4 on 2025-09-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_restaurant_estimated_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
