# Generated by Django 5.2.4 on 2025-09-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_experience_estimated_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='itineraries', to='travel.tag'),
        ),
    ]
