# Generated by Django 5.2.4 on 2025-09-15 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_destinationview'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationview',
            name='action_type',
            field=models.CharField(choices=[('view', 'View'), ('dwell', 'Dwell'), ('click', 'Click')], default='view', max_length=10),
        ),
        migrations.AddField(
            model_name='destinationview',
            name='click_target',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destinationview',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='travel.destination'),
        ),
    ]
