# Generated by Django 5.2.4 on 2025-09-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('travel', '0007_rating'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['content_type', 'object_id'], name='travel_rati_content_bfd338_idx'),
        ),
    ]
