# Generated by Django 5.2.4 on 2025-09-16 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_rating_travel_rati_content_bfd338_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
