# Generated by Django 5.2.4 on 2025-09-16 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_destinationview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='day_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='travel.dayplan'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='day_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='travel.dayplan'),
        ),
        migrations.AddIndex(
            model_name='destinationview',
            index=models.Index(fields=['user', 'destination', 'action_type'], name='travel_dest_user_id_57ae32_idx'),
        ),
    ]
