# Generated by Django 5.2.4 on 2025-09-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_alter_attraction_day_plan_alter_restaurant_day_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='highlighted_places',
            field=models.TextField(db_index=True, help_text='Comma-separated values like Beach, Fort'),
        ),
    ]
