# Generated by Django 5.2.4 on 2025-09-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_alter_attraction_name_alter_destination_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attraction',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attraction',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
