# Generated by Django 5.2.4 on 2025-09-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_attraction_city_attraction_country_attraction_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='city',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='country',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='state',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='country',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='state',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, db_index=True, max_length=100)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'unique_together': {('city', 'state', 'country')},
            },
        ),
    ]
