# Generated by Django 5.2.4 on 2025-09-17 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_remove_attraction_city_remove_attraction_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attractions', to='travel.location'),
        ),
        migrations.AddField(
            model_name='destination',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations', to='travel.location'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='travel.location'),
        ),
    ]
