# Generated by Django 5.2.4 on 2025-09-21 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_attraction_location_destination_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='google_place_id',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='longitude',
        ),
        migrations.AddField(
            model_name='experience',
            name='attraction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='travel.attraction'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='day_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_experiences', to='travel.dayplan'),
        ),
    ]
