# Generated by Django 5.2.4 on 2025-09-21 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_attractionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='day_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attractions', to='travel.dayplan'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='day_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='travel.dayplan'),
        ),
    ]
