# Generated by Django 5.2.4 on 2025-09-23 18:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_alter_attraction_day_plan_alter_restaurant_day_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractionimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
