# Generated by Django 5.2.4 on 2025-09-23 18:17

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_alter_attractionimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='attractionimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='attractions/'),
        ),
    ]
