# Generated by Django 5.2.4 on 2025-09-23 18:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_alter_attraction_image_alter_attractionimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractionimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
