# Generated by Django 5.2.4 on 2025-09-23 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0021_remove_itinerary_thumbnail_itinerary_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
