# Generated by Django 5.2.4 on 2025-09-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0023_destinationimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='short_description',
            field=models.TextField(blank=True, help_text='A short summary of the itinerary for cards/list views (2–3 lines).'),
        ),
    ]
