# Generated by Django 5.2.4 on 2025-09-25 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0024_itinerary_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.category'),
        ),
    ]
