# Generated by Django 5.2.4 on 2025-09-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0025_attraction_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='category',
        ),
        migrations.AddField(
            model_name='attraction',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='attractions', to='travel.category'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='itineraries', to='travel.category'),
        ),
    ]
