# Generated by Django 5.2.4 on 2025-09-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0026_remove_attraction_category_remove_itinerary_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
