# Generated by Django 5.2.4 on 2025-09-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0028_itinerary_author_type_itinerary_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='is_trending',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
