# Generated by Django 5.2.4 on 2025-09-26 16:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0029_alter_destination_is_trending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationview',
            name='action_type',
            field=models.CharField(choices=[('view', 'View'), ('dwell', 'Dwell'), ('click', 'Click')], db_index=True, default='view', max_length=10),
        ),
        migrations.AlterField(
            model_name='destinationview',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='duration_days',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='popularity_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='total_budget',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
    ]
