# Generated by Django 5.2.4 on 2025-09-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0030_alter_destinationview_action_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['day_plan'], name='travel_attr_day_pla_753eae_idx'),
        ),
        migrations.AddIndex(
            model_name='daybudget',
            index=models.Index(fields=['day_plan'], name='travel_dayb_day_pla_7cfd15_idx'),
        ),
        migrations.AddIndex(
            model_name='dayplan',
            index=models.Index(fields=['itinerary'], name='travel_dayp_itinera_19f61f_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['destination', 'id'], name='travel_itin_destina_edcc5e_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['destination', 'total_budget', 'duration_days'], name='travel_itin_destina_82aca1_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['country'], name='travel_loca_country_d981e9_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['day_plan'], name='travel_rest_day_pla_443a06_idx'),
        ),
    ]
