# Generated by Django 5.2.4 on 2025-09-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0031_attraction_travel_attr_day_pla_753eae_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='favoriteitinerary',
            index=models.Index(fields=['user', 'itinerary'], name='travel_favo_user_id_a3e7f1_idx'),
        ),
    ]
