# Generated by Django 5.2.4 on 2025-10-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0033_itinerary_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='trending_score',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
