# Generated by Django 5.2.4 on 2025-10-02 15:49

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0034_destination_trending_score'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['location', 'name'], name='travel_attr_locatio_b302f2_idx'),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='attraction_name_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
