# Generated by Django 5.2.4 on 2025-10-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0035_attraction_travel_attr_locatio_b302f2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attraction',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attraction',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['city'], name='travel_attr_city_56d30f_idx'),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['state'], name='travel_attr_state_5706fe_idx'),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['country'], name='travel_attr_country_5a6012_idx'),
        ),
    ]
